#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app_lucky_number:
    #path: /lucky/number
    #controller: App\Controller\LuckyController::number

app_catalog_show:
    path: /catalog/show
    controller: App\Controller\CatalogController::show

blog_yaml:
 path: /blog_yaml/{page}
 controller: App\Controller\BlogController::list_yaml
 requirements:
  page: '\d+'